---
deployment:
  tasks:
    - export DEPLOYPATH=/home/username/public_html/
    - /bin/cp -R * $DEPLOYPATH
    - /bin/cp .htaccess $DEPLOYPATH
    - /bin/cp requirements.txt $DEPLOYPATH
    
    # If you're using a Python virtual environment
    - source $DEPLOYPATH/venv/bin/activate
    - pip install -r $DEPLOYPATH/requirements.txt
    
    # If you need to run database migrations
    - cd $DEPLOYPATH
    - flask db upgrade