"""Add price offered to room requests

Revision ID: 055a4c15979d
Revises: bc876f6c7b9b
Create Date: 2024-10-09 12:47:38.568257

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '055a4c15979d'
down_revision = 'bc876f6c7b9b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('room_request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price_offered', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('room_request', schema=None) as batch_op:
        batch_op.drop_column('price_offered')

    # ### end Alembic commands ###
