"""Notes added to room model

Revision ID: 05d4bfe308b3
Revises: df6d20963322
Create Date: 2024-08-27 12:58:15.621817

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05d4bfe308b3'
down_revision = 'df6d20963322'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('room', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notes', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('room', schema=None) as batch_op:
        batch_op.drop_column('notes')

    # ### end Alembic commands ###
