"""Add credit columns to Agency

Revision ID: 12f975743853
Revises: 9a081586ac1d
Create Date: 2024-09-04 16:24:14.765608

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12f975743853'
down_revision = '9a081586ac1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agencies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('credit_limit', sa.Numeric(precision=12, scale=2), nullable=True))
        batch_op.add_column(sa.Column('used_credit', sa.Numeric(precision=12, scale=2), nullable=True))
        batch_op.add_column(sa.Column('paid_back', sa.Numeric(precision=12, scale=2), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agencies', schema=None) as batch_op:
        batch_op.drop_column('paid_back')
        batch_op.drop_column('used_credit')
        batch_op.drop_column('credit_limit')

    # ### end Alembic commands ###
