"""Add payment number of vendor on a booking

Revision ID: 14eda469beec
Revises: 8019965c2631
Create Date: 2024-09-27 17:24:44.703610

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14eda469beec'
down_revision = '8019965c2631'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_number', sa.String(length=64), nullable=True))
        batch_op.create_unique_constraint('uq_payment_number', ['payment_number'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_constraint('uq_payment_number', type_='unique')
        batch_op.drop_column('payment_number')

    # ### end Alembic commands ###
