"""Add role field to User model

Revision ID: 453fa01c2885
Revises: ad3bc5423147
Create Date: 2024-09-04 11:52:27.827052

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '453fa01c2885'
down_revision = 'ad3bc5423147'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agencies', schema=None) as batch_op:
        batch_op.drop_column('user_id')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(length=64), nullable=False, server_default='default_role'))

    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('role')

    with op.batch_alter_table('agencies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            'fk_agencies_user_id_users',  # Give a meaningful name for the constraint
            'users', ['user_id'], ['id']
        )