"""Add weekend rates for every month

Revision ID: 4a5760074a62
Revises: c72042d81205
Create Date: 2024-05-22 01:37:24.314888

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a5760074a62'
down_revision = 'c72042d81205'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('room', schema=None) as batch_op:
        batch_op.add_column(sa.Column('weekend_rates_addition', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('room', schema=None) as batch_op:
        batch_op.drop_column('weekend_rates_addition')

    # ### end Alembic commands ###
