"""Add special requests to booking_

Revision ID: 51b5c197d4f1
Revises: d9613d9041d9
Create Date: 2024-09-17 15:37:45.872199

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51b5c197d4f1'
down_revision = 'd9613d9041d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('special_requests', sa.String(length=128), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_column('special_requests')

    # ### end Alembic commands ###
