"""Add View status to Booking REquest

Revision ID: 5fc4e98a5680
Revises: 8e9e553486d1
Create Date: 2024-10-02 17:28:58.395284

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5fc4e98a5680'
down_revision = '8e9e553486d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking_request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('view_status', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking_request', schema=None) as batch_op:
        batch_op.drop_column('view_status')

    # ### end Alembic commands ###
