"""Add status to Booking request

Revision ID: 62e59d0074d0
Revises: cb9ba2d9e7ec
Create Date: 2024-09-30 18:55:26.732512

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62e59d0074d0'
down_revision = 'cb9ba2d9e7ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking_request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking_request', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
