"""Add discount to Booking

Revision ID: 8e9e553486d1
Revises: 62e59d0074d0
Create Date: 2024-10-02 14:06:12.813444

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e9e553486d1'
down_revision = '62e59d0074d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('discount', sa.Numeric(precision=12, scale=2), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_column('discount')

    # ### end Alembic commands ###
