"""Add stars to Hotel

Revision ID: 9949bdb04c4e
Revises: 51b5c197d4f1
Create Date: 2024-09-25 13:24:15.113424

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9949bdb04c4e'
down_revision = '51b5c197d4f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hotel', schema=None) as batch_op:
        # Step 1: Add the column without the NOT NULL constraint
        batch_op.add_column(sa.Column('stars', sa.Integer(), nullable=True))

    # Step 2: Set a default value for existing rows
    op.execute('UPDATE hotel SET stars = 1 WHERE stars IS NULL')

    # Step 3: Alter the column to be NOT NULL
    with op.batch_alter_table('hotel', schema=None) as batch_op:
        batch_op.alter_column('stars', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hotel', schema=None) as batch_op:
        batch_op.drop_column('stars')
    # ### end Alembic commands ###
