"""Add image to Hotel

Revision ID: 9a14bf0b7ee2
Revises: 05d4bfe308b3
Create Date: 2024-08-27 14:24:30.850206

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a14bf0b7ee2'
down_revision = '05d4bfe308b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hotel', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hotel', schema=None) as batch_op:
        batch_op.drop_column('image')

    # ### end Alembic commands ###
