"""Add Booking requests model

Revision ID: 9c3807e3fea3
Revises: 9249ffad2250
Create Date: 2024-09-30 15:12:05.201556

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c3807e3fea3'
down_revision = '9249ffad2250'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('booking_request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hotel_name', sa.String(length=128), nullable=False),
    sa.Column('room_type', sa.String(length=128), nullable=False),
    sa.Column('check_in', sa.Date(), nullable=False),
    sa.Column('check_out', sa.Date(), nullable=False),
    sa.Column('guest_name', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('booking_request')
    # ### end Alembic commands ###
