"""Add allowed_accounts to Agency model

Revision ID: a67198414641
Revises: dd1ed8cc921e
Create Date: 2024-09-05 14:50:52.483694

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a67198414641'
down_revision = 'dd1ed8cc921e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agencies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('allowed_accounts', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agencies', schema=None) as batch_op:
        batch_op.drop_column('allowed_accounts')

    # ### end Alembic commands ###
