"""Add room_type back to booking

Revision ID: aa0704b0bce6
Revises: b34ae5022ab4
Create Date: 2024-09-11 14:43:09.762239

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa0704b0bce6'
down_revision = 'b34ae5022ab4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('room_type', sa.String(length=128), nullable=True))
        batch_op.alter_column('room_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.alter_column('room_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('room_type')

    # ### end Alembic commands ###
