"""Add weekend rates for every month and rooms available

Revision ID: c72042d81205
Revises: df50c160a1b4
Create Date: 2024-05-22 01:32:48.536998

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c72042d81205'
down_revision = 'df50c160a1b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('room', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rooms_available', sa.Integer()))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('room', schema=None) as batch_op:
        batch_op.drop_column('rooms_available')

    # ### end Alembic commands ###
