"""Add special requests and approval to room_

Revision ID: d9613d9041d9
Revises: aa0704b0bce6
Create Date: 2024-09-17 13:57:45.449589

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9613d9041d9'
down_revision = 'aa0704b0bce6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.alter_column('room_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('room', schema=None) as batch_op:
        batch_op.add_column(sa.Column('approval', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('room', schema=None) as batch_op:
        batch_op.drop_column('approval')

    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.alter_column('room_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
