"""Remove certain fields from Room model

Revision ID: df50c160a1b4
Revises: 76ad2a4a098b
Create Date: 2024-05-20 04:48:54.446027

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df50c160a1b4'
down_revision = '76ad2a4a098b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('room', schema=None) as batch_op:
        batch_op.drop_column('price')
        batch_op.drop_column('check_out')
        batch_op.drop_column('check_in')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('room', schema=None) as batch_op:
        batch_op.add_column(sa.Column('check_in', sa.DATETIME(), nullable=False))
        batch_op.add_column(sa.Column('check_out', sa.DATETIME(), nullable=False))
        batch_op.add_column(sa.Column('price', sa.FLOAT(), nullable=False))

    # ### end Alembic commands ###
