"""empty message

Revision ID: df6d20963322
Revises: c4cbaffceb7b
Create Date: 2024-05-29 04:22:37.534432

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = 'df6d20963322'
down_revision = 'c4cbaffceb7b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('room', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_price', sa.Float(), nullable=True))
        batch_op.alter_column('availability',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('rooms_available',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('january_rates',
               existing_type=sa.TEXT(),
               type_=sqlite.JSON(),
               existing_nullable=True)
        batch_op.alter_column('february_rates',
               existing_type=sa.TEXT(),
               type_=sqlite.JSON(),
               existing_nullable=True)
        batch_op.alter_column('march_rates',
               existing_type=sa.TEXT(),
               type_=sqlite.JSON(),
               existing_nullable=True)
        batch_op.alter_column('april_rates',
               existing_type=sa.TEXT(),
               type_=sqlite.JSON(),
               existing_nullable=True)
        batch_op.alter_column('may_rates',
               existing_type=sa.TEXT(),
               type_=sqlite.JSON(),
               existing_nullable=True)
        batch_op.alter_column('june_rates',
               existing_type=sa.TEXT(),
               type_=sqlite.JSON(),
               existing_nullable=True)
        batch_op.alter_column('july_rates',
               existing_type=sa.TEXT(),
               type_=sqlite.JSON(),
               existing_nullable=True)
        batch_op.alter_column('august_rates',
               existing_type=sa.TEXT(),
               type_=sqlite.JSON(),
               existing_nullable=True)
        batch_op.alter_column('september_rates',
               existing_type=sa.TEXT(),
               type_=sqlite.JSON(),
               existing_nullable=True)
        batch_op.alter_column('october_rates',
               existing_type=sa.TEXT(),
               type_=sqlite.JSON(),
               existing_nullable=True)
        batch_op.alter_column('november_rates',
               existing_type=sa.TEXT(),
               type_=sqlite.JSON(),
               existing_nullable=True)
        batch_op.alter_column('december_rates',
               existing_type=sa.TEXT(),
               type_=sqlite.JSON(),
               existing_nullable=True)
        batch_op.drop_column('weekend_rates_addition')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('room', schema=None) as batch_op:
        batch_op.add_column(sa.Column('weekend_rates_addition', sqlite.JSON(), nullable=True))
        batch_op.alter_column('december_rates',
               existing_type=sqlite.JSON(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('november_rates',
               existing_type=sqlite.JSON(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('october_rates',
               existing_type=sqlite.JSON(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('september_rates',
               existing_type=sqlite.JSON(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('august_rates',
               existing_type=sqlite.JSON(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('july_rates',
               existing_type=sqlite.JSON(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('june_rates',
               existing_type=sqlite.JSON(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('may_rates',
               existing_type=sqlite.JSON(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('april_rates',
               existing_type=sqlite.JSON(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('march_rates',
               existing_type=sqlite.JSON(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('february_rates',
               existing_type=sqlite.JSON(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('january_rates',
               existing_type=sqlite.JSON(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('rooms_available',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('availability',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.drop_column('total_price')

    # ### end Alembic commands ###
