"""Add account_limit to Agency

Revision ID: f9d3b0c174fc
Revises: 4932679d6f64
Create Date: 2024-09-04 19:12:52.604540

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9d3b0c174fc'
down_revision = '4932679d6f64'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agencies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('account_limit', sa.Numeric(precision=5, scale=0), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agencies', schema=None) as batch_op:
        batch_op.drop_column('account_limit')

    # ### end Alembic commands ###
