"""Add Times confirmation number and check on bookings

Revision ID: fab9ed0940df
Revises: 0435baf69e21
Create Date: 2024-09-26 16:37:48.987567

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fab9ed0940df'
down_revision = '0435baf69e21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('times_con_number', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('times_confirmed', sa.Boolean(), nullable=True))
        batch_op.create_unique_constraint('uq_times_con_number', ['times_con_number'])  # Give a name to the constraint

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_constraint('uq_times_con_number', type_='unique')  # Use the same name to drop the constraint
        batch_op.drop_column('times_confirmed')
        batch_op.drop_column('times_con_number')

    # ### end Alembic commands ###
